# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75edefabeaa23b5ed06451ea6ad92d530ba322eae573f791ea9ce8a9702ea3d76cf4fe79b165417a5acd892064ebacc355f84a41e3b38dc44fd6008e878cd53b

test:
  secret_key_base: 54e555b130d74e4ae461f5bf820ccd44cc7d44f8f5d44a65c5a7c49386dd3e06788aa8479b1a5a2c4b2cb7938d613a1262fedbd5983558df60acabbc9e08e243

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
